from django.urls import path
from django.views.generic.base import RedirectView
from .views import *

urlpatterns = [
    path('educationinfo/<int:user>/', EducationInfo.as_view(), name='education_info'),
    path('educationinfo/<int:user>/othereducations/', RedirectView.as_view(url='../#other-educations'), name='other_educations'),
    path('educationinfo/<int:user>/certifications/', RedirectView.as_view(url='../#certifications'), name='certifications'),
    path('educationinfo/<int:user>/skills/', RedirectView.as_view(url='../#skills'), name='skills'),
    path('educationinfo/<int:user>/languages/', RedirectView.as_view(url='../#languages'), name='languages'),
    path('othereducation/', RedirectView.as_view(url='../educationinfo/self/#other-educations')),
    path('othereducation/add/', AddOtherEducation.as_view(), name='add_other_education'),
    path('othereducation/<int:pk>/', RedirectView.as_view(url='change/')),
    path('othereducation/<int:pk>/change/', ChangeOtherEducation.as_view(), name='change_other_education'),
    path('othereducation/<int:pk>/delete/', DeleteOtherEducation.as_view(), name='delete_other_education'),
    path('certification/', RedirectView.as_view(url='../educationinfo/self/#certifications')),
    path('certification/add/', AddCertification.as_view(), name='add_certification'),
    path('certification/<int:pk>/', RedirectView.as_view(url='change/')),
    path('certification/<int:pk>/change/', ChangeCertification.as_view(), name='change_certification'),
    path('certification/<int:pk>/delete/', DeleteCertification.as_view(), name='delete_certification'),
    path('skill/', RedirectView.as_view(url='../educationinfo/self/#skills')),
    path('skill/<int:user>/add/', AddSkill.as_view(), name='add_skill'),
    path('skill/<int:user>/<int:pk>/delete/', DeleteSkill.as_view(), name='delete_skill'),
    path('language/', RedirectView.as_view(url='../educationinfo/self/#languages')),
    path('language/<int:user>/add/', AddLanguage.as_view(), name='add_language'),
    path('language/<int:user>/<int:pk>/delete/', DeleteLanguage.as_view(), name='delete_language'),
    path('experienceinfo/<int:user>/', ExperienceInfo.as_view(), name='experience_info'),
    path('experienceinfo/<int:user>/workexperiences/', RedirectView.as_view(url='../#workexperience'), name='work_experiences'),
    path('experienceinfo/<int:user>/projects/', RedirectView.as_view(url='../#projects'), name='projects'),
    path('workexperience/', RedirectView.as_view(url='../experienceinfo/self/#workexperience')),
    path('workexperience/add/', AddWorkExperience.as_view(), name='add_work_experience'),
    path('workexperience/<int:pk>/', RedirectView.as_view(url='change/')),
    path('workexperience/<int:pk>/change/', ChangeWorkExperience.as_view(), name='change_work_experience'),
    path('workexperience/<int:pk>/delete/', DeleteWorkExperience.as_view(), name='delete_work_experience'),
    path('project/', RedirectView.as_view(url='../experienceinfo/self/#projects')),
    path('project/add/', AddProject.as_view(), name='add_project'),
    path('project/<int:pk>/', RedirectView.as_view(url='change/')),
    path('project/<int:pk>/change/', ChangeProject.as_view(), name='change_project'),
    path('project/<int:pk>/delete/', DeleteProject.as_view(), name='delete_project'),
    path('ipinfo/<int:user>/', IPInfo.as_view(), name='ip_info'),
    path('ipinfo/<int:user>/patents/', RedirectView.as_view(url='../#patents'), name='patents'),
    path('ipinfo/<int:user>/publications/', RedirectView.as_view(url='../#publications'), name='publications'),
    path('patent/', RedirectView.as_view(url='../ipinfo/self/#patents')),
    path('patent/add/', AddPatent.as_view(), name='add_patent'),
    path('patent/<int:pk>/', RedirectView.as_view(url='change/')),
    path('patent/<int:pk>/change/', ChangePatent.as_view(), name='change_patent'),
    path('patent/<int:pk>/delete/', DeletePatent.as_view(), name='delete_patent'),
    path('publication/', RedirectView.as_view(url='../ipinfo/self/#publications')),
    path('publication/add/', AddPublication.as_view(), name='add_publication'),
    path('publication/<int:pk>/', RedirectView.as_view(url='change/')),
    path('publication/<int:pk>/change/', ChangePublication.as_view(), name='change_publication'),
    path('publication/<int:pk>/delete/', DeletePublication.as_view(), name='delete_publication'),
    path('otherinfo/<int:user>/', OtherInfos.as_view(), name='other_info'),
    path('otherinfo/<int:user>/achievements/', RedirectView.as_view(url='..#achievements'), name='achievements'),
    path('otherinfo/<int:user>/presentations/', RedirectView.as_view(url='..#presentations'), name='presentations'),
    path('otherinfo/<int:user>/otherinfos/', RedirectView.as_view(url='../#other-info'), name='other_infos'),
    path('achievement/', RedirectView.as_view(url='../otherinfo/self/#achievements')),
    path('achievement/add/', AddAchievement.as_view(), name='add_achievement'),
    path('achievement/<int:pk>/', RedirectView.as_view(url='change/')),
    path('achievement/<int:pk>/change/', ChangeAchievement.as_view(), name='change_achievement'),
    path('achievement/<int:pk>/delete/', DeleteAchievement.as_view(), name='delete_achievement'),
    path('presentation/', RedirectView.as_view(url='../otherinfo/self/#presentations')),
    path('presentation/add/', AddPresentation.as_view(), name='add_presentation'),
    path('presentation/<int:pk>/', RedirectView.as_view(url='change/')),
    path('presentation/<int:pk>/change/', ChangePresentation.as_view(), name='change_presentation'),
    path('presentation/<int:pk>/delete/', DeletePresentation.as_view(), name='delete_presentation'),
    path('otherinfo/', RedirectView.as_view(url='../otherinfo/self/#other-info')),
    path('otherinfo/add/', AddOtherInfo.as_view(), name='add_other_info'),
    path('otherinfo/<int:pk>/', RedirectView.as_view(url='change/')),
    path('otherinfo/<int:pk>/change/', ChangeOtherInfo.as_view(), name='change_other_info'),
    path('otherinfo/<int:pk>/delete/', DeleteOtherInfo.as_view(), name='delete_other_info'),
    path('skillautocomplete/', SkillAutocomplete.as_view(), name='skill_autocomplete'),
    path('languageautocomplete/', LanguageAutocomplete.as_view(), name='language_autocomplete'),
]