from django.urls import path
from django.views.generic.base import RedirectView
from .views import *

urlpatterns = [
    path('', SelfUser.as_view(), name='self_user'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('list/skillautocomplete/', SkillAutocomplete.as_view(), name='user_list_skill_autocomplete'),
    path('list/csv/', UserCSVView.as_view(), name='user_csv'),
    path('signin/', SignIn.as_view(), name='sign_in'),
    path('signout/', SignOut.as_view(), name='sign_out'),
    path('resetpassword/<str:email>/<str:code>/', ResetPassword.as_view(), name='reset_password'),
    path('<int:pk>/', BuildProfile.as_view(), name='build_profile'),
    path('<int:pk>/approve/', ApproveUser.as_view(), name='approve_user'),
    path('<int:pk>/reject/', RejectUser.as_view(), name='reject_user'),
    path('<int:pk>/makesuperuser/', MakeSuperUser.as_view(), name='make_superuser'),
    path('<int:pk>/makecoordinator/', MakeCoordinator.as_view(), name='make_coordinator'),
    path('<int:pk>/removecoordinator/', RemoveCoordinator.as_view(), name='remove_coordinator'),
    path('<int:pk>/makequoter/', MakeQuoter.as_view(), name='make_quoter'),
    path('<int:pk>/removequoter/', RemoveQuoter.as_view(), name='remove_quoter'),
    path('<int:pk>/makeclassrep/', MakeClassRep.as_view(), name='make_cr'),
    path('<int:pk>/removeclassrep/', RemoveClassRep.as_view(), name='remove_cr'),
    path('<int:pk>/makehod/', MakeHOD.as_view(), name='make_hod'),
    path('<int:pk>/maketpchead/', MakeTPCHead.as_view(), name='make_tpc_head'),
    path('<int:pk>/resume/', Resume.as_view(), name='resume'),
    path('<int:pk>/personal/', PersonalContactInfo.as_view(), name='personal_contact_info'),
    path('<int:pk>/personal/phone-numbers/', RedirectView.as_view(url='../#phone-numbers'), name='phone_numbers'),
    path('<int:pk>/personal/emails/', RedirectView.as_view(url='../#emails'), name='emails'),
    path('<int:pk>/personal/addresses/', RedirectView.as_view(url='../#addresses'), name='addresses'),
    path('<int:pk>/personal/links/', RedirectView.as_view(url='../#links'), name='links'),
    path('<int:pk>/change/', ChangeUser.as_view(), name='change_user'),
    path('<int:pk>/setprimaryphonenumber/<int:phone_number>/', SetPrimaryPhoneNumber.as_view(), name='set_primary_phone_number'),
    path('<int:pk>/setprimaryemail/<str:email>/', SetPrimaryEmail.as_view(), name='set_primary_email'),
    path('<int:pk>/setprimaryaddress/<int:address>/', SetPrimaryAddress.as_view(), name='set_primary_address'),
    path('phonenumber/add/', AddPhoneNumber.as_view(), name='add_phone_number'),
    path('phonenumber/<int:pk>/delete/', DeletePhoneNumber.as_view(), name='delete_phone_number'),
    path('email/add/', AddEmail.as_view(), name='add_email'),
    path('email/<str:pk>/delete/', DeleteEmail.as_view(), name='delete_email'),
    path('email/<str:pk>/<str:code>/', VerifyEmail.as_view(), name='verify_email'),
    path('address/add/', AddAddress.as_view(), name='add_address'),
    path('address/<int:pk>/', RedirectView.as_view(url='change/')),
    path('address/<int:pk>/change/', ChangeAddress.as_view(), name='change_address'),
    path('address/<int:pk>/delete/', DeleteAddress.as_view(), name='delete_address'),
    path('link/add/', AddLink.as_view(), name='add_link'),
    path('link/<str:pk>/delete/', DeleteLink.as_view(), name='delete_link'),
]